require "nokogiri"
require "open-uri"
require "pry"

require_relative "../lib/standardize_address"
require_relative "../lib/standardize_address/cli"
require_relative "../lib/standardize_address/verify"
#require_relative "../lib/standardize_address/track"
require_relative "../lib/standardize_address/scraper"
require_relative "../lib/standardize_address/version"
